-- =============================================================================
-- PayNest schema-v1.sql
-- Live session 2026-07-16 — Step 2 worked example (code-first migrations)
-- =============================================================================
--
-- WHERE THIS FILE COMES FROM
--   We wrote these tables by reading the Java classes in
--   src/main/java/com/paynestsystem/domain/ — NOT by exporting from draw.io.
--   The draw.io ERD in this folder is only a picture to help you visualise.
--
-- WHAT IS A "MIGRATION"?
--   A migration is a carefully written piece of SQL that changes the database
--   structure (create tables, add columns, add constraints). Version "v1"
--   means "first shape of the database for this session."
--
-- HOW YOU WILL USE THIS LATER (Capstone 4)
--   Copy or adapt these statements into H2Schema.java (or keep a .sql artefact)
--   and run them once when your app starts, using JDBC.
--
-- DATABASE
--   File-backed H2: jdbc:h2:file:./data/paynest
--   Files land under the gitignored ./data/ folder.
--
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PART A — CAPSTONE 4 / 5 (required for durable payments)
-- Java sources:
--   TransactionRecord.java, Transaction.java, TransactionStatus.java,
--   AiDecisionRecord.java, RiskLevel.java
-- -----------------------------------------------------------------------------

-- transaction_records
-- --------------------
-- Java: TransactionRecord wraps a Transaction plus identity, status, and
-- support fields. In SQL we FLATTEN the nested Transaction into columns
-- (amount, bank, transaction_timestamp) so one row = one durable attempt.
--
-- Why UNIQUE on idempotency_key?
--   Capstone 4: the same client key must never create a second posted attempt.
--   The database enforces that with UNIQUE — even if your Java forgets a check.

CREATE TABLE IF NOT EXISTS transaction_records (
    -- TransactionRecord.id (String) — stable identity for this attempt
    id                      VARCHAR(64)   NOT NULL,

    -- TransactionRecord.idempotencyKey — business key from upstream retries
    idempotency_key         VARCHAR(128)  NOT NULL,

    -- Flattened from Transaction.amount
    amount                  DOUBLE        NOT NULL,

    -- Flattened from Transaction.bank
    bank                    VARCHAR(64)   NOT NULL,

    -- Flattened from Transaction.timestamp (when the payment attempt was created)
    transaction_timestamp   TIMESTAMP     NOT NULL,

    -- TransactionRecord.status — stored as text; values match the Java enum:
    -- PENDING, ROUTED, COMPLETED, FAILED
    status                  VARCHAR(32)   NOT NULL,

    -- TransactionRecord.createdAt / updatedAt
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL,

    -- Optional support / Capstone 5 fields (nullable = allowed to be unknown)
    routing_summary         VARCHAR(512),
    assessed_risk           VARCHAR(16),   -- LOW, MEDIUM, HIGH (RiskLevel)
    monitoring_flag         BOOLEAN       NOT NULL DEFAULT FALSE,
    ai_assessment_summary   CLOB,

    -- PRIMARY KEY: exactly one row per id; the main way we look up a record
    CONSTRAINT pk_transaction_records PRIMARY KEY (id),

    -- UNIQUE: the database rejects a second row with the same key
    CONSTRAINT uq_transaction_records_idempotency UNIQUE (idempotency_key)
);

-- Helpful lookup when resolving an idempotency key to a record id
CREATE INDEX IF NOT EXISTS idx_transaction_records_idempotency
    ON transaction_records (idempotency_key);

-- Helpful for operational reports that group by status
CREATE INDEX IF NOT EXISTS idx_transaction_records_status
    ON transaction_records (status);


-- ai_decision_records
-- --------------------
-- Java: AiDecisionRecord — Capstone 5 audit trail for AI-assisted risk.
-- The Java class does not have its own id field; tables usually still need one
-- so each audit row is uniquely addressable. We add id as IDENTITY (auto number).

CREATE TABLE IF NOT EXISTS ai_decision_records (
    -- Extra relational key (not on the Java class yet — that is OK)
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY,

    -- AiDecisionRecord.transactionRecordId → transaction_records.id
    transaction_record_id   VARCHAR(64)   NOT NULL,

    -- AiDecisionRecord.createdAt
    created_at              TIMESTAMP     NOT NULL,

    -- AiDecisionRecord.rawAiPayload — can be large; CLOB = "character large object"
    raw_ai_payload          CLOB,

    -- AiDecisionRecord.resolvedRiskLevel — LOW, MEDIUM, HIGH
    resolved_risk_level     VARCHAR(16)   NOT NULL,

    -- AiDecisionRecord.usedFallback
    used_fallback           BOOLEAN       NOT NULL,

    CONSTRAINT pk_ai_decision_records PRIMARY KEY (id),

    -- FOREIGN KEY: every AI row must point at a real transaction_records row
    CONSTRAINT fk_ai_decision_transaction
        FOREIGN KEY (transaction_record_id)
        REFERENCES transaction_records (id)
);

CREATE INDEX IF NOT EXISTS idx_ai_decision_transaction
    ON ai_decision_records (transaction_record_id);


-- =============================================================================
-- PART B — CAPSTONE 1 COMMERCE (OPTIONAL for Capstone 4)
-- =============================================================================
-- Capstone 1 keeps Product / Customer / Order in memory today.
-- These tables are here so you can practise mapping classes → SQL.
-- You do NOT need Part B to pass Capstone 4 unless your instructor says otherwise.
-- Uncomment the block below if you want to create commerce tables too.
-- =============================================================================

/*
CREATE TABLE IF NOT EXISTS customers (
    -- Customer.id
    id      INT           NOT NULL,
    -- Customer.name
    name    VARCHAR(128)  NOT NULL,
    -- Customer.email
    email   VARCHAR(256)  NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS products (
    -- Product.id
    id      INT           NOT NULL,
    -- Product.name
    name    VARCHAR(128)  NOT NULL,
    -- Product.price
    price   DOUBLE        NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
    -- Order.id
    id           INT  NOT NULL,
    -- Order.customer → Customer.id (relationship becomes a foreign key column)
    customer_id  INT  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    -- OrderItem has no id in Java; we use a composite key
    -- (order_id + product_id) meaning "this product on this order".
    order_id    INT  NOT NULL,
    product_id  INT  NOT NULL,
    -- OrderItem.quantity
    quantity    INT  NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (id)
);
*/
